/**
 * Casual Maze Game - Constants & Enumerations
 */

export const TILES = Object.freeze({
  FLOOR: 0,
  WALL: 1,
  BRIDGE_EW: 'B_EW',
  BRIDGE_NS: 'B_NS',
  RAMP_N: 'R_N',
  RAMP_S: 'R_S',
  RAMP_E: 'R_E',
  RAMP_W: 'R_W',
});

export const ENTITY_TYPES = Object.freeze({
  KEY: 'key',
  DOOR: 'door',
  LEVER: 'lever',
});

export const LAYERS = Object.freeze({
  GROUND: 'ground',
  OVERHEAD: 'overhead',
});

export const ELEVATION = Object.freeze({
  GROUND: 0,
  OVERHEAD: 1,
});

export const FOG_STATE = Object.freeze({
  UNEXPLORED: 0,
  EXPLORED: 1,
  VISIBLE: 2,
});

export const DIRECTIONS = Object.freeze({
  NORTH: { x: 0, y: -1, name: 'north' },
  SOUTH: { x: 0, y: 1, name: 'south' },
  WEST: { x: -1, y: 0, name: 'west' },
  EAST: { x: 1, y: 0, name: 'east' },
});

export const OPPOSITE_DIRECTIONS = Object.freeze({
  north: 'south',
  south: 'north',
  west: 'east',
  east: 'west',
});

export const KEY_CODES = Object.freeze({
  UP: ['ArrowUp', 'KeyW', 'KeyK', 'w', 'W', 'k', 'K', 'Up'],
  DOWN: ['ArrowDown', 'KeyS', 'KeyJ', 's', 'S', 'j', 'J', 'Down'],
  LEFT: ['ArrowLeft', 'KeyA', 'KeyH', 'a', 'A', 'h', 'H', 'Left'],
  RIGHT: ['ArrowRight', 'KeyD', 'KeyL', 'd', 'D', 'l', 'L', 'Right'],
  INTERACT: ['Space', 'KeyE', 'Enter', 'e', 'E', ' ', 'Enter'],
  MAP: ['KeyM', 'm', 'M'],
  RESTART: ['KeyR', 'r', 'R'],
  PAUSE: ['Escape', 'KeyP', 'p', 'P', 'Esc'],
});

export const KEY_COLORS = Object.freeze({
  GOLD: '#fbbf24',
  RED: '#f43f5e',
  BLUE: '#38bdf8',
  GREEN: '#34d399',
  PURPLE: '#a855f7',
});

export const DEFAULTS = Object.freeze({
  TILE_SIZE: 32,
  VIEW_RADIUS: 6,
  FOG_OF_WAR: true,
  MAP_REVEALED: false,
  ALLOW_FREE_PAN: true,
  CAMERA_LERP: 0.12,
  PLAYER_SPEED: 4.8, // tiles per second during smooth walk
  MINIMAP_SIZE: 180,
  THEME: 'dungeon',
});

export const THEMES = Object.freeze({
  dungeon: {
    id: 'dungeon',
    name: 'Dungeon',
    icon: '🏰',
    bg: '#0d1117',
    floor: '#161b22',
    floorAlt: '#1c2128',
    floorGrid: 'rgba(255, 255, 255, 0.03)',
    wall: '#30363d',
    wallTop: '#484f58',
    wallDetail: '#21262d',
    bridgeGround: '#1e293b',
    bridgeOverhead: '#475569',
    bridgeRailing: '#94a3b8',
    ramp: '#334155',
    rampArrow: '#38bdf8',
    accent: '#38bdf8',
    portalOuter: '#0284c7',
    portalInner: '#38bdf8',
    fogUnexplored: '#05070a',
    fogMemory: 'rgba(5, 7, 10, 0.65)',
  },
  jungle: {
    id: 'jungle',
    name: 'Emerald Jungle',
    icon: '🌴',
    bg: '#051811',
    floor: '#0b291d',
    floorAlt: '#0f3827',
    floorGrid: 'rgba(52, 211, 153, 0.04)',
    wall: '#14532d',
    wallTop: '#22c55e',
    wallDetail: '#166534',
    bridgeGround: '#3f2e18',
    bridgeOverhead: '#78350f',
    bridgeRailing: '#34d399',
    ramp: '#15803d',
    rampArrow: '#4ade80',
    accent: '#10b981',
    portalOuter: '#059669',
    portalInner: '#34d399',
    fogUnexplored: '#020b08',
    fogMemory: 'rgba(2, 11, 8, 0.65)',
  },
  emerald: {
    id: 'emerald',
    name: 'Emerald Cavern',
    icon: '🌴',
    bg: '#051811',
    floor: '#0b291d',
    floorAlt: '#0f3827',
    floorGrid: 'rgba(52, 211, 153, 0.04)',
    wall: '#14532d',
    wallTop: '#22c55e',
    wallDetail: '#166534',
    bridgeGround: '#3f2e18',
    bridgeOverhead: '#78350f',
    bridgeRailing: '#34d399',
    ramp: '#15803d',
    rampArrow: '#4ade80',
    accent: '#10b981',
    portalOuter: '#059669',
    portalInner: '#34d399',
    fogUnexplored: '#020b08',
    fogMemory: 'rgba(2, 11, 8, 0.65)',
  },
  lava: {
    id: 'lava',
    name: 'Molten Core',
    icon: '🌋',
    bg: '#1c0a06',
    floor: '#2a110a',
    floorAlt: '#38160c',
    floorGrid: 'rgba(249, 115, 22, 0.05)',
    wall: '#451a03',
    wallTop: '#ea580c',
    wallDetail: '#7c2d12',
    bridgeGround: '#1c1917',
    bridgeOverhead: '#292524',
    bridgeRailing: '#f97316',
    ramp: '#7c2d12',
    rampArrow: '#fb923c',
    accent: '#f97316',
    portalOuter: '#dc2626',
    portalInner: '#f97316',
    fogUnexplored: '#0a0402',
    fogMemory: 'rgba(10, 4, 2, 0.65)',
  },
  snow: {
    id: 'snow',
    name: 'Glacial Expanse',
    icon: '❄️',
    bg: '#08141e',
    floor: '#0e2333',
    floorAlt: '#132f45',
    floorGrid: 'rgba(56, 189, 248, 0.05)',
    wall: '#1e3a5f',
    wallTop: '#38bdf8',
    wallDetail: '#0284c7',
    bridgeGround: '#0c1e2e',
    bridgeOverhead: '#1e40af',
    bridgeRailing: '#93c5fd',
    ramp: '#0369a1',
    rampArrow: '#67e8f9',
    accent: '#06b6d4',
    portalOuter: '#0284c7',
    portalInner: '#67e8f9',
    fogUnexplored: '#040b12',
    fogMemory: 'rgba(4, 11, 18, 0.65)',
  },
  cave: {
    id: 'cave',
    name: 'Amethyst Caverns',
    icon: '🔮',
    bg: '#120b1e',
    floor: '#1f1333',
    floorAlt: '#291942',
    floorGrid: 'rgba(168, 85, 247, 0.05)',
    wall: '#4c1d95',
    wallTop: '#c084fc',
    wallDetail: '#581c87',
    bridgeGround: '#2e1065',
    bridgeOverhead: '#6b21a8',
    bridgeRailing: '#d8b4fe',
    ramp: '#581c87',
    rampArrow: '#e879f9',
    accent: '#a855f7',
    portalOuter: '#7e22ce',
    portalInner: '#d8b4fe',
    fogUnexplored: '#08040d',
    fogMemory: 'rgba(8, 4, 13, 0.65)',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset Citadel',
    icon: '🌅',
    bg: '#180e15',
    floor: '#2a1622',
    floorAlt: '#351c2b',
    floorGrid: 'rgba(244, 63, 94, 0.04)',
    wall: '#632541',
    wallTop: '#f43f5e',
    wallDetail: '#831843',
    bridgeGround: '#4a152d',
    bridgeOverhead: '#831843',
    bridgeRailing: '#f472b6',
    ramp: '#701a75',
    rampArrow: '#fb7185',
    accent: '#f43f5e',
    portalOuter: '#be185d',
    portalInner: '#fb7185',
    fogUnexplored: '#0c070b',
    fogMemory: 'rgba(12, 7, 11, 0.65)',
  },
});

export const ZONES = Object.freeze({
  tutorial: {
    id: 'tutorial',
    title: 'Tutorial Academy',
    badge: '🎓 Academy',
    icon: '🎓',
    theme: 'dungeon',
    desc: 'Step-by-step training mastering movement, colored keys, mechanisms, bridges, and fog of war.',
  },
  zone_1: {
    id: 'zone_1',
    title: 'Zone 1: Whispering Dungeon',
    badge: '🏰 Tier 1',
    icon: '🏰',
    theme: 'dungeon',
    desc: 'Ancient stone labyrinth exploring multi-elevation crossings and lever-locked crypts.',
  },
  zone_2: {
    id: 'zone_2',
    title: 'Zone 2: Emerald Jungle',
    badge: '🌴 Tier 2',
    icon: '🌴',
    theme: 'jungle',
    desc: 'Lush canopy mazes with rope bridge walkways, dense foliage barriers, and multiple colored gates.',
  },
  zone_3: {
    id: 'zone_3',
    title: 'Zone 3: Molten Core',
    badge: '🌋 Tier 3',
    icon: '🌋',
    theme: 'lava',
    desc: 'Intense volcanic vaults with obsidian bridges spanning over magma channels and dynamic switch gates.',
  },
  zone_4: {
    id: 'zone_4',
    title: 'Zone 4: Glacial Expanse',
    badge: '❄️ Tier 4',
    icon: '❄️',
    theme: 'snow',
    desc: 'Chiseled frost caverns with slippery ice passages, crystal trestles, and shrouded blizzards.',
  },
  zone_5: {
    id: 'zone_5',
    title: 'Zone 5: Amethyst Caverns',
    badge: '🔮 Tier 5',
    icon: '🔮',
    theme: 'cave',
    desc: 'Bioluminescent deep subterranean ruins with multi-tier bridges and intricate key-lever sequences.',
  },
});
