/**
 * Casual Maze Game — Storylines & Episodic Quests Registry
 *
 * Defines first-class narrative story campaigns alongside the mainline megalabyrinths.
 * Transforms tutorials into "The Novice's Initiation" and introduces thematic quests.
 */

import { TUTORIAL_LEVELS } from '../levels/tutorials.js';
import { TILES } from '../core/constants.js';

// Story 1: The Novice's Initiation (Chapters 1 to 6)
const NOVICE_CHAPTER_PROLOGUES = [
  {
    chapter: 1,
    title: 'The Waking Hall',
    subtitle: 'Orientation & First Footing',
    prologue: 'The ancient oak doors seal behind you. The elder cartographers whisper: "Every grand journey begins with a single step. Trust your senses and seek the azure exit portal."',
    hint: 'Use WASD or Arrow keys to move through the stone hall to the glowing blue portal.',
  },
  {
    chapter: 2,
    title: 'The Prismatic Gates',
    subtitle: 'Color Resonance & Sealed Portals',
    prologue: 'Glimmering keystones radiate faint elemental auras in the damp corridors. Only keys forged in the same hue can break the resonance seals of locked sanctuary doors.',
    hint: 'Collect the colored keys to unlock matching barriers blocking your path.',
  },
  {
    chapter: 3,
    title: 'Clockwork Mechanisms',
    subtitle: 'Dynamic Architecture & Levers',
    prologue: 'Heavy bronze levers groan under centuries of silence. Throwing a lever engages subterranean clockwork, sliding solid stone walls into the earth.',
    hint: 'Step onto levers to dynamically lower walls and open alternative corridors.',
  },
  {
    chapter: 4,
    title: 'The Canopy Crossing',
    subtitle: 'Multi-Elevation Bridges & Ramps',
    prologue: 'Wooden ramps ascend into the soaring canopy. At elevation, you can cross high above ground pathways, defying the maze’s 2D constraints.',
    hint: 'Ascend directional ramps (▲) to cross overhead bridges over lower passages.',
  },
  {
    chapter: 5,
    title: 'The Shrouded Vaults',
    subtitle: 'Dynamic Fog of War & Spatial Memory',
    prologue: 'Deep subterranean darkness envelops the corridors. Keep your wits sharp and trace the labyrinth in your mind as shadows conceal what lies ahead.',
    hint: 'Navigate through dynamic line-of-sight fog. Use the walls you have seen to navigate.',
  },
  {
    chapter: 6,
    title: "The Guildmaster's Rite",
    subtitle: 'The Final Synthesis Trial',
    prologue: 'All lessons converge in the grand proving grounds. Combine key resonance, mechanical switches, and overhead bridges to claim the title of Journeyman Pathfinder.',
    hint: 'Synthesize all your skills to solve this master labyrinth and complete your initiation.',
  },
];

// Enrich tutorial levels into first-class Story chapters
const NOVICE_INITIATION_CHAPTERS = TUTORIAL_LEVELS.map((level, idx) => {
  const meta = NOVICE_CHAPTER_PROLOGUES[idx];
  return {
    ...level,
    storyId: 'novice_initiation',
    chapterNumber: idx + 1,
    chapterTitle: meta.title,
    chapterSubtitle: meta.subtitle,
    prologueText: meta.prologue,
    help: {
      title: `${meta.title} (Chapter ${idx + 1}/6)`,
      message: `${meta.prologue}\n\nObjective: ${meta.hint}`,
    },
  };
});

// Story 2: Relics of the Four Guardians (3 Chapters)
const GUARDIANS_CHAPTER_1 = {
  "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
  "id": "story_guardians_1",
  "version": 1,
  "storyId": "relics_of_the_guardians",
  "chapterNumber": 1,
  "chapterTitle": "The Whispering Ruins",
  "chapterSubtitle": "Inscriptions, Relic Gems & Respawn Beacons",
  "prologueText": "You arrive at the outer perimeter of the Sunken Sun Temple. Weathered wall carvings whisper forgotten lore, while pulsing respawn beacons promise sanctuary amidst ancient fire traps.",
  "title": "The Whispering Ruins",
  "author": "Ancient Guild of Cartographers",
  "dimensions": {
    "width": 11,
    "height": 11
  },
  "config": {
    "fogOfWar": false,
    "mapRevealed": true,
    "viewRadius": 7,
    "allowFreePan": true,
    "tileSize": 32,
    "theme": "temple"
  },
  "help": {
    "title": "Chapter 1: The Whispering Ruins",
    "message": "Inspect wall carvings [E], collect bonus sun gems, activate the respawn beacon, and safely bypass the flame vents."
  },
  "spawn": {
    "x": 1,
    "y": 1,
    "elevation": 0,
    "style": "stairs_down"
  },
  "exit": {
    "x": 9,
    "y": 9,
    "elevation": 0,
    "style": "portal"
  },
  "parSteps": 28,
  "parTime": 17,
  "layers": {
    "ground": [
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        1
      ],
      [
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        1
      ],
      [
        1,
        1,
        1,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        1
      ],
      [
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ]
    ],
    "overhead": [
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    ]
  },
  "entities": [
    {
      "id": "wall_note_entry",
      "type": "wall_decor",
      "decorType": "note",
      "text": "The Four Guardians sleep in the temple heart. Heed the stone plinths.",
      "playerDialogue": "An ancient inscription... it speaks of four guardian totems.",
      "x": 1,
      "y": 2,
      "elevation": 0
    },
    {
      "id": "gem_sun_1",
      "type": "collectible",
      "collectibleType": "gem",
      "name": "Sunstone Crystal",
      "scoreValue": 150,
      "x": 3,
      "y": 1,
      "elevation": 0
    },
    {
      "id": "chk_ruins_beacon",
      "type": "checkpoint",
      "name": "Outer Ruins Beacon",
      "x": 5,
      "y": 1,
      "elevation": 0
    },
    {
      "id": "hazard_fire_1",
      "type": "timed_hazard",
      "hazardType": "fire_vent",
      "activeDuration": 1200,
      "period": 2600,
      "offset": 0,
      "x": 7,
      "y": 1,
      "elevation": 0
    },
    {
      "id": "key_ruins_gold",
      "type": "key",
      "color": "#fbbf24",
      "name": "Golden Sun Key",
      "x": 9,
      "y": 1,
      "elevation": 0
    },
    {
      "id": "door_ruins_gold",
      "type": "door",
      "requiresKey": "key_ruins_gold",
      "color": "#fbbf24",
      "name": "Sun Sanctum Gate",
      "x": 5,
      "y": 6,
      "elevation": 0
    },
    {
      "id": "gem_sun_2",
      "type": "collectible",
      "collectibleType": "gem",
      "name": "Solar Amber",
      "scoreValue": 200,
      "x": 1,
      "y": 9,
      "elevation": 0
    },
    {
      "id": "wall_note_exit",
      "type": "wall_decor",
      "decorType": "carving",
      "text": "The Falcon watches from the winds of the eastern terrace.",
      "playerDialogue": "The first guardian is the Falcon...",
      "x": 7,
      "y": 9,
      "elevation": 0
    }
  ]
};

const GUARDIANS_CHAPTER_2 = {
  "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
  "id": "story_guardians_2",
  "version": 1,
  "storyId": "relics_of_the_guardians",
  "chapterNumber": 2,
  "chapterTitle": "The Falcon's Plinth",
  "chapterSubtitle": "Carryable Relics & Riddle Sockets",
  "prologueText": "You stand before the Terrace of the Winds. An empty carved pedestal blocks the gate to the inner sanctuary. You must find the lost Falcon Statue, carry it across the terrace, and seat it on its sacred plinth.",
  "title": "The Falcon's Plinth",
  "author": "Ancient Guild of Cartographers",
  "dimensions": {
    "width": 11,
    "height": 11
  },
  "config": {
    "fogOfWar": false,
    "mapRevealed": true,
    "viewRadius": 7,
    "allowFreePan": true,
    "tileSize": 32,
    "theme": "temple"
  },
  "help": {
    "title": "Chapter 2: The Falcon's Plinth",
    "message": "Pick up the Falcon Statue [E], carry it through the labyrinth, and place it on the inscribed pedestal to unlock the courtyard gate."
  },
  "spawn": {
    "x": 1,
    "y": 1,
    "elevation": 0,
    "style": "stairs_down"
  },
  "exit": {
    "x": 9,
    "y": 9,
    "elevation": 0,
    "style": "portal"
  },
  "parSteps": 32,
  "parTime": 19,
  "layers": {
    "ground": [
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1
      ],
      [
        1,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        1,
        1,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        1,
        0,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ]
    ],
    "overhead": [
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    ]
  },
  "entities": [
    {
      "id": "statue_falcon",
      "type": "riddle_item",
      "name": "Falcon Statue",
      "itemStyle": "falcon",
      "symbol": "🦅",
      "description": "A finely carved marble statue of the mountain falcon.",
      "x": 1,
      "y": 5,
      "elevation": 0
    },
    {
      "id": "wall_falcon_clue",
      "type": "wall_decor",
      "decorType": "carving",
      "text": "Only when the winged sentinel overlooks the winds will the gate open.",
      "playerDialogue": "The inscription describes the Falcon pedestal!",
      "x": 3,
      "y": 3,
      "elevation": 0
    },
    {
      "id": "ped_falcon",
      "type": "pedestal",
      "name": "Sky Plinth",
      "pedestalStyle": "plinth",
      "riddleHint": "Place the Falcon upon this plinth to unlock the terrace gate.",
      "acceptedItemId": "statue_falcon",
      "puzzleGroupId": "group_falcon_terrace",
      "targetDoorId": "door_terrace_gate",
      "x": 7,
      "y": 3,
      "elevation": 0
    },
    {
      "id": "door_terrace_gate",
      "type": "door",
      "color": "#38bdf8",
      "name": "Terrace Gate",
      "x": 7,
      "y": 6,
      "elevation": 0
    },
    {
      "id": "gem_terrace",
      "type": "collectible",
      "collectibleType": "gem",
      "name": "Sky Sapphire",
      "scoreValue": 250,
      "x": 9,
      "y": 5,
      "elevation": 0
    },
    {
      "id": "chk_terrace",
      "type": "checkpoint",
      "name": "Terrace Haven",
      "x": 4,
      "y": 3,
      "elevation": 0
    }
  ]
};

const GUARDIANS_CHAPTER_3 = {
  "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
  "id": "story_guardians_3",
  "version": 1,
  "storyId": "relics_of_the_guardians",
  "chapterNumber": 3,
  "chapterTitle": "Sanctum of the Four Guardians",
  "chapterSubtitle": "The Grand Environmental Riddle",
  "prologueText": "You enter the sacred Grand Sanctum. Four ornate plinths stand before the Golden Gate of Eternity. Four guardian statues—Falcon, Lion, Serpent, and Bear—must each be retrieved from their alcoves and positioned according to the sacred verses to open the gate.",
  "title": "Sanctum of the Four Guardians",
  "author": "Ancient Guild of Cartographers",
  "dimensions": {
    "width": 15,
    "height": 15
  },
  "config": {
    "fogOfWar": false,
    "mapRevealed": true,
    "viewRadius": 8,
    "allowFreePan": true,
    "tileSize": 32,
    "theme": "temple"
  },
  "help": {
    "title": "Chapter 3: Sanctum of the Four Guardians",
    "message": "Read the riddle inscriptions on the 4 pedestals [E]. Carry and place Falcon, Lion, Serpent, and Bear into their matching plinths to unlock the Grand Sanctum Gate."
  },
  "spawn": {
    "x": 7,
    "y": 1,
    "elevation": 0,
    "style": "stairs_down"
  },
  "exit": {
    "x": 7,
    "y": 13,
    "elevation": 0,
    "style": "portal"
  },
  "parSteps": 54,
  "parTime": 33,
  "layers": {
    "ground": [
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        0,
        0,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1
      ],
      [
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        0,
        1,
        1
      ],
      [
        1,
        0,
        0,
        0,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ]
    ],
    "overhead": [
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    ]
  },
  "entities": [
    {
      "id": "chk_sanctum_heart",
      "type": "checkpoint",
      "name": "Sanctum Altar Beacon",
      "x": 7,
      "y": 5,
      "elevation": 0
    },
    {
      "id": "riddle_falcon_s3",
      "type": "riddle_item",
      "name": "Falcon Statue",
      "itemStyle": "falcon",
      "symbol": "🦅",
      "description": "The ancient totem of the open skies and north wind.",
      "x": 1,
      "y": 3,
      "elevation": 0
    },
    {
      "id": "riddle_lion_s3",
      "type": "riddle_item",
      "name": "Lion Statue",
      "itemStyle": "lion",
      "symbol": "🦁",
      "description": "The solar totem crowned with blazing mane.",
      "x": 1,
      "y": 11,
      "elevation": 0
    },
    {
      "id": "riddle_serpent_s3",
      "type": "riddle_item",
      "name": "Serpent Statue",
      "itemStyle": "serpent",
      "symbol": "🐍",
      "description": "The emerald totem of winding subterranean waters.",
      "x": 13,
      "y": 3,
      "elevation": 0
    },
    {
      "id": "riddle_bear_s3",
      "type": "riddle_item",
      "name": "Bear Statue",
      "itemStyle": "bear",
      "symbol": "🐻",
      "description": "The iron totem of enduring mountains and stone.",
      "x": 13,
      "y": 11,
      "elevation": 0
    },
    {
      "id": "ped_sky",
      "type": "pedestal",
      "name": "Plinth of the Winds",
      "pedestalStyle": "plinth",
      "riddleHint": "First Verse: He who soars highest watches from the North.",
      "acceptedItemId": "riddle_falcon_s3",
      "puzzleGroupId": "guardians_sanctum_group",
      "targetDoorId": "door_sanctum_gate",
      "x": 5,
      "y": 7,
      "elevation": 0
    },
    {
      "id": "ped_fire",
      "type": "pedestal",
      "name": "Plinth of the Sun",
      "pedestalStyle": "altar",
      "riddleHint": "Second Verse: The golden hunter with burning mane guards the West.",
      "acceptedItemId": "riddle_lion_s3",
      "puzzleGroupId": "guardians_sanctum_group",
      "targetDoorId": "door_sanctum_gate",
      "x": 6,
      "y": 7,
      "elevation": 0
    },
    {
      "id": "ped_water",
      "type": "pedestal",
      "name": "Plinth of Waters",
      "pedestalStyle": "plinth",
      "riddleHint": "Third Verse: The coiled serpent of the deep springs sleeps in the East.",
      "acceptedItemId": "riddle_serpent_s3",
      "puzzleGroupId": "guardians_sanctum_group",
      "targetDoorId": "door_sanctum_gate",
      "x": 8,
      "y": 7,
      "elevation": 0
    },
    {
      "id": "ped_earth",
      "type": "pedestal",
      "name": "Plinth of Mountains",
      "pedestalStyle": "altar",
      "riddleHint": "Fourth Verse: The stalwart bear of iron earth stands at the South.",
      "acceptedItemId": "riddle_bear_s3",
      "puzzleGroupId": "guardians_sanctum_group",
      "targetDoorId": "door_sanctum_gate",
      "x": 9,
      "y": 7,
      "elevation": 0
    },
    {
      "id": "door_sanctum_gate",
      "type": "door",
      "color": "#fbbf24",
      "name": "Golden Sanctum Gate",
      "x": 7,
      "y": 10,
      "elevation": 0
    },
    {
      "id": "wall_sanctum_proclamation",
      "type": "wall_decor",
      "decorType": "carving",
      "text": "Four guardians kept the peace of the realm. Place each where its spirit belongs.",
      "playerDialogue": "The riddle verses on the four plinths will guide which statue belongs where.",
      "x": 7,
      "y": 3,
      "elevation": 0
    }
  ]
};

// Story 3: The Whispering Citadel (Multi-Room Dungeon)
const CITADEL_CHAPTER_1 = {
  "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
  "id": "story_citadel_1",
  "storyId": "the_whispering_citadel",
  "chapterNumber": 1,
  "chapterTitle": "The Whispering Citadel",
  "chapterSubtitle": "Interconnected Multi-Room Sanctuary",
  "prologueText": "Beneath the peaks of the Monolith lies the Whispering Citadel—a three-tier sanctuary connecting an ancient courtyard, subterranean catacombs, and a high spire open to the four winds.",
  "title": "The Whispering Citadel",
  "author": "High Cartographer of the Monolith",
  "version": 1,
  "dimensions": {
    "width": 13,
    "height": 13
  },
  "config": {
    "fogOfWar": true,
    "viewRadius": 6,
    "allowFreePan": true,
    "tileSize": 32,
    "theme": "temple",
    "viewPerspective": "angled"
  },
  "spawn": {
    "x": 1,
    "y": 1,
    "elevation": 0,
    "style": "stairs_down"
  },
  "exit": {
    "x": 11,
    "y": 11,
    "elevation": 0,
    "style": "portal",
    "label": "Apex Altar of the Monolith"
  },
  "exits": [
    {
      "id": "exit_courtyard_to_catacombs",
      "x": 1,
      "y": 11,
      "elevation": 0,
      "style": "stairs",
      "label": "Descend into Catacombs",
      "targetRoom": "catacombs",
      "targetSpawn": {
        "x": 1,
        "y": 1,
        "elevation": 0
      }
    },
    {
      "id": "exit_courtyard_to_spire",
      "x": 11,
      "y": 11,
      "elevation": 0,
      "style": "stairs",
      "label": "Ascend to High Spire",
      "targetRoom": "high_spire",
      "targetSpawn": {
        "x": 1,
        "y": 1,
        "elevation": 0
      }
    }
  ],
  "initialRoom": "courtyard",
  "rooms": {
    "courtyard": {
      "id": "courtyard",
      "title": "Grand Courtyard",
      "theme": "temple",
      "dimensions": {
        "width": 13,
        "height": 13
      },
      "spawn": {
        "x": 1,
        "y": 1,
        "elevation": 0,
        "style": "stairs_down"
      },
      "exits": [
        {
          "id": "exit_courtyard_to_catacombs",
          "x": 1,
          "y": 11,
          "elevation": 0,
          "style": "stairs",
          "label": "Descend into Catacombs",
          "targetRoom": "catacombs",
          "targetSpawn": {
            "x": 1,
            "y": 1,
            "elevation": 0
          }
        },
        {
          "id": "exit_courtyard_to_spire",
          "x": 11,
          "y": 11,
          "elevation": 0,
          "style": "stairs",
          "label": "Ascend to High Spire",
          "targetRoom": "high_spire",
          "targetSpawn": {
            "x": 1,
            "y": 1,
            "elevation": 0
          }
        }
      ],
      "layers": {
        "ground": [
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            1,
            1,
            1,
            1,
            0,
            1,
            1,
            1,
            1,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            1
          ],
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ]
        ],
        "overhead": [
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ]
        ]
      },
      "entities": [
        {
          "id": "signpost_courtyard_guide",
          "type": "signpost",
          "title": "Courtyard Inscription",
          "message": "The High Spire awaits above, but its portal is sealed. Descend into the subterranean Catacombs to recover the Spire Key.",
          "x": 2,
          "y": 1,
          "elevation": 0
        },
        {
          "id": "door_spire_gate",
          "type": "door",
          "color": "#06b6d4",
          "name": "Spire Barrier Gate",
          "requiresKey": "key_citadel_spire",
          "x": 11,
          "y": 10,
          "elevation": 0
        },
        {
          "id": "decor_courtyard_statue",
          "type": "wall_decor",
          "decorType": "carving",
          "title": "Shrine of the Winds",
          "text": "Four winds echo through the citadel. Turn your perspective to catch their secrets.",
          "author": "Ancient Cartographer",
          "x": 6,
          "y": 1,
          "facing": "south",
          "elevation": 0
        },
        {
          "id": "gem_courtyard_topaz",
          "type": "collectible",
          "collectibleType": "gem",
          "name": "Courtyard Topaz",
          "scoreValue": 150,
          "color": "#fbbf24",
          "x": 11,
          "y": 1,
          "elevation": 0
        }
      ]
    },
    "catacombs": {
      "id": "catacombs",
      "title": "Sunken Catacombs",
      "theme": "dungeon",
      "dimensions": {
        "width": 13,
        "height": 13
      },
      "spawn": {
        "x": 1,
        "y": 1,
        "elevation": 0,
        "style": "stairs_down"
      },
      "exits": [
        {
          "id": "exit_catacombs_to_courtyard",
          "x": 1,
          "y": 1,
          "elevation": 0,
          "style": "stairs",
          "label": "Return to Courtyard",
          "targetRoom": "courtyard",
          "targetSpawn": {
            "x": 1,
            "y": 10,
            "elevation": 0
          }
        }
      ],
      "layers": {
        "ground": [
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ]
        ],
        "overhead": [
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ]
        ]
      },
      "entities": [
        {
          "id": "key_citadel_spire",
          "type": "key",
          "color": "#06b6d4",
          "name": "Spire Keystone",
          "x": 11,
          "y": 11,
          "elevation": 0
        },
        {
          "id": "hazard_catacomb_fire",
          "type": "hazard",
          "hazardType": "fire",
          "cyclePeriod": 3000,
          "offsetRatio": 0,
          "x": 6,
          "y": 5,
          "elevation": 0
        },
        {
          "id": "wall_decor_catacomb_carving",
          "type": "wall_decor",
          "decorType": "carving",
          "title": "Catacomb Epitaph",
          "text": "Here lie the guardians who sealed the high spire away from the reaching fog.",
          "author": "Unknown Cryptkeeper",
          "x": 4,
          "y": 1,
          "facing": "south",
          "elevation": 0
        },
        {
          "id": "gem_crypt_amethyst",
          "type": "collectible",
          "collectibleType": "gem",
          "name": "Catacomb Amethyst",
          "scoreValue": 250,
          "color": "#a855f7",
          "x": 11,
          "y": 1,
          "elevation": 0
        }
      ]
    },
    "high_spire": {
      "id": "high_spire",
      "title": "Whispering Spire",
      "theme": "snow",
      "dimensions": {
        "width": 13,
        "height": 13
      },
      "spawn": {
        "x": 1,
        "y": 1,
        "elevation": 0,
        "style": "stairs_down"
      },
      "exits": [
        {
          "id": "exit_spire_to_courtyard",
          "x": 1,
          "y": 1,
          "elevation": 0,
          "style": "stairs",
          "label": "Descend to Courtyard",
          "targetRoom": "courtyard",
          "targetSpawn": {
            "x": 11,
            "y": 9,
            "elevation": 0
          }
        },
        {
          "id": "exit_spire_citadel_victory",
          "x": 11,
          "y": 11,
          "elevation": 0,
          "style": "portal",
          "label": "Apex Altar of the Monolith"
        },
        {
          "id": "exit_spire_secret_monolith",
          "x": 11,
          "y": 1,
          "elevation": 0,
          "style": "portal",
          "label": "Secret Monolith Tunnel",
          "targetLevel": "29"
        }
      ],
      "layers": {
        "ground": [
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            "R_E",
            0,
            0,
            0,
            0,
            0,
            "R_W",
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ]
        ],
        "overhead": [
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            "B_NS",
            "B_NS",
            "B_NS",
            "B_NS",
            "B_NS",
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
          ],
          [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ]
        ]
      },
      "entities": [
        {
          "id": "checkpoint_spire_altar",
          "type": "checkpoint",
          "style": "shrine",
          "name": "Spire Apex Waypoint",
          "x": 6,
          "y": 6,
          "elevation": 1,
          "color": "#38bdf8"
        },
        {
          "id": "gem_spire_sapphire",
          "type": "collectible",
          "collectibleType": "gem",
          "name": "Star of the Monolith",
          "scoreValue": 500,
          "color": "#38bdf8",
          "x": 6,
          "y": 11,
          "elevation": 0
        },
        {
          "id": "wall_decor_spire_revelation",
          "type": "wall_decor",
          "decorType": "carving",
          "title": "Apex Revelation",
          "text": "From the heights of the spire, the entire world bends beneath your perspective. Rotate [Q / R] to survey the horizons.",
          "author": "High Cartographer",
          "x": 6,
          "y": 1,
          "facing": "south",
          "elevation": 0
        }
      ]
    }
  },
  "parSteps": 80,
  "parTime": 60,
  "architectNote": "A true multi-room dungeon. Descend into the Catacombs to retrieve the Spire Key, return to unlock the Spire Gate, and ascend to the mountain heights.",
  "help": {
    "title": "The Whispering Citadel",
    "message": "Travel between the Courtyard, Catacombs, and High Spire. Your inventory, score, and key state persist between rooms!"
  },
  "layers": {
    "ground": [
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ]
    ],
    "overhead": [
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ]
    ]
  },
  "entities": [
    {
      "id": "signpost_courtyard_guide",
      "type": "signpost",
      "title": "Courtyard Inscription",
      "message": "The High Spire awaits above, but its portal is sealed. Descend into the subterranean Catacombs to recover the Spire Key.",
      "x": 2,
      "y": 1,
      "elevation": 0
    },
    {
      "id": "door_spire_gate",
      "type": "door",
      "color": "#06b6d4",
      "name": "Spire Barrier Gate",
      "requiresKey": "key_citadel_spire",
      "x": 11,
      "y": 10,
      "elevation": 0
    },
    {
      "id": "decor_courtyard_statue",
      "type": "wall_decor",
      "decorType": "carving",
      "title": "Shrine of the Winds",
      "text": "Four winds echo through the citadel. Turn your perspective to catch their secrets.",
      "author": "Ancient Cartographer",
      "x": 6,
      "y": 1,
      "facing": "south",
      "elevation": 0
    },
    {
      "id": "gem_courtyard_topaz",
      "type": "collectible",
      "collectibleType": "gem",
      "name": "Courtyard Topaz",
      "scoreValue": 150,
      "color": "#fbbf24",
      "x": 11,
      "y": 1,
      "elevation": 0
    }
  ]
};

export const STORYLINES = Object.freeze([
  {
    id: 'the_whispering_citadel',
    title: 'The Whispering Citadel',
    tagline: 'Delve into an interconnected three-tier labyrinth with rotating vantage points.',
    description: 'Explore the mysterious Citadel beneath the Monolith. Descend into damp catacombs to retrieve the Spire Key, navigate back to the Courtyard to unlock the grand stairwell, and ascend into the Whispering Spire.',
    badge: 'Dungeon Saga • Multi-Room',
    icon: '🏛️',
    accentColor: '#10b981',
    theme: 'temple',
    difficulty: 'Advanced',
    totalChapters: 1,
    chapters: [CITADEL_CHAPTER_1],
  },

  {
    id: 'novice_initiation',
    title: "The Novice's Initiation",
    tagline: 'Master the ancient art of labyrinth navigation and earn your pathfinder badge.',
    description: 'Follow the rite of passage designed by the ancient Guild of Cartographers. Progress through six structured chambers to learn line-of-sight, colored gates, dynamic levers, overhead canopy bridges, and the shrouded fog of war.',
    badge: 'Prologue • 6 Chapters',
    icon: '📜',
    accentColor: '#38bdf8',
    theme: 'dungeon',
    difficulty: 'Introductory',
    totalChapters: 6,
    chapters: NOVICE_INITIATION_CHAPTERS,
  },
  {
    id: 'relics_of_the_guardians',
    title: 'Relics of the Four Guardians',
    tagline: 'Recover the sacred animal totems and unlock the sealed sanctum.',
    description: 'Journey into the Sunken Sun Temple. Decipher wall inscriptions, collect sunstone crystals, activate respawn beacons, and place the four sacred guardian statues—Falcon, Lion, Serpent, and Bear—onto their matching riddle plinths.',
    badge: 'Riddle Quest • 3 Chapters',
    icon: '🦅',
    accentColor: '#fbbf24',
    theme: 'temple',
    difficulty: 'Intermediate',
    totalChapters: 3,
    chapters: [GUARDIANS_CHAPTER_1, GUARDIANS_CHAPTER_2, GUARDIANS_CHAPTER_3],
  },
]);

/**
 * Retrieve a storyline by ID
 * @param {string} storyId
 * @returns {object|null}
 */
export function getStoryline(storyId) {
  if (!storyId) return null;
  return STORYLINES.find(s => s.id === storyId) || null;
}

/**
 * Retrieve a specific chapter from a storyline
 * @param {string} storyId
 * @param {number} chapterNumber (1-indexed)
 * @returns {object|null}
 */
export function getStoryChapter(storyId, chapterNumber) {
  const story = getStoryline(storyId);
  if (!story) return null;
  const num = parseInt(chapterNumber, 10);
  if (isNaN(num) || num < 1 || num > story.chapters.length) return null;
  return story.chapters[num - 1] || null;
}

/**
 * Get next chapter info in a storyline
 * @param {string} storyId
 * @param {number} currentChapterNumber (1-indexed)
 * @returns {{ hasNext: boolean, nextChapterNumber?: number, nextChapter?: object, isStoryComplete: boolean }}
 */
export function getNextStoryChapter(storyId, currentChapterNumber) {
  const story = getStoryline(storyId);
  if (!story) {
    return { hasNext: false, isStoryComplete: false };
  }
  const curr = parseInt(currentChapterNumber, 10);
  if (curr < story.totalChapters) {
    return {
      hasNext: true,
      nextChapterNumber: curr + 1,
      nextChapter: story.chapters[curr],
      isStoryComplete: false,
    };
  }
  return {
    hasNext: false,
    isStoryComplete: true,
  };
}

/**
 * Get all story levels flattened into an array
 * @returns {Array<object>}
 */
export function getAllStoryLevels() {
  const all = [];
  for (const story of STORYLINES) {
    for (const chapter of story.chapters) {
      all.push(chapter);
    }
  }
  return all;
}
