/**
 * Casual Maze Game - Campaign Chapter 3 Levels
 */

export const CAMPAIGN_CH3_LEVELS = Object.freeze([
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "9",
    "chapter": "chapter_3",
    "zone": "zone_3",
    "title": "The Iron Lever",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 15,
      "height": 13
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "temple"
    },
    "spawn": {
      "x": 2,
      "y": 2,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 12,
      "y": 9,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 28,
    "parTime": 17,
    "architectNote": "The bronze lever awakens the sleeping clockwork. Throw the switch to slide the heavy stone barrier into the floor.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          1,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_9",
        "type": "signpost",
        "x": 3,
        "y": 2,
        "z": 0,
        "title": "Architect's Note #9",
        "text": "The bronze lever awakens the sleeping clockwork. Throw the switch to slide the heavy stone barrier into the floor.",
        "style": "stone_tablet"
      },
      {
        "id": "lever_9",
        "type": "lever",
        "name": "Iron Foundry Lever",
        "style": "switch_lever",
        "x": 2,
        "y": 8,
        "elevation": 0,
        "state": false,
        "targets": [
          {
            "action": "toggle_tile",
            "layer": "ground",
            "x": 10,
            "y": 5,
            "stateA": 0,
            "stateB": 1
          }
        ]
      },
      {
        "id": "wall_gear_carving_9",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "Pistons roar beneath the stone when the iron lever clicks.",
        "playerDialogue": "The lever on the left must control the eastern barrier.",
        "x": 2,
        "y": 6,
        "elevation": 0
      },
      {
        "id": "gem_clockwork_9",
        "type": "collectible",
        "collectibleType": "gem",
        "name": "Bronze Gear Relic",
        "scoreValue": 150,
        "x": 12,
        "y": 4,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "10",
    "chapter": "chapter_3",
    "zone": "zone_3",
    "title": "Clockwork Gates",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 17,
      "height": 15
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "temple"
    },
    "spawn": {
      "x": 3,
      "y": 2,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 9,
      "y": 12,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 41,
    "parTime": 25,
    "architectNote": "Dual conduits power the hydraulic gates. Engage the western valve to unlock the concourse, then release the eastern master piston.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          0,
          1,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_10",
        "type": "signpost",
        "x": 4,
        "y": 2,
        "z": 0,
        "title": "Architect's Note #10",
        "text": "Dual conduits power the hydraulic gates. Engage the western valve to unlock the concourse, then release the eastern master piston.",
        "style": "stone_tablet"
      },
      {
        "id": "lever_10_west",
        "type": "lever",
        "name": "Western Hydraulic Valve",
        "style": "switch_lever",
        "x": 2,
        "y": 7,
        "elevation": 0,
        "state": false,
        "targets": [
          {
            "action": "toggle_tile",
            "layer": "ground",
            "x": 6,
            "y": 5,
            "stateA": 0,
            "stateB": 1
          }
        ]
      },
      {
        "id": "lever_10_east",
        "type": "lever",
        "name": "Eastern Steam Piston",
        "style": "switch_lever",
        "x": 14,
        "y": 7,
        "elevation": 0,
        "state": false,
        "targets": [
          {
            "action": "toggle_tile",
            "layer": "ground",
            "x": 9,
            "y": 10,
            "stateA": 0,
            "stateB": 1
          }
        ]
      },
      {
        "id": "wall_note_10",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "Conduit sequence: West powers Concourse, East unlocks South.",
        "playerDialogue": "The western valve opens the central chamber.",
        "x": 3,
        "y": 5,
        "elevation": 0
      },
      {
        "id": "gem_clockwork_10",
        "type": "collectible",
        "collectibleType": "gem",
        "name": "Brass Dynamo Core",
        "scoreValue": 200,
        "x": 14,
        "y": 4,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "11",
    "chapter": "chapter_3",
    "zone": "zone_3",
    "title": "Shifting Foundations",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 17,
      "height": 15
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "temple"
    },
    "spawn": {
      "x": 2,
      "y": 2,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 13,
      "y": 12,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 30,
    "parTime": 18,
    "architectNote": "The master valve is balanced upon a counterweight: as the northern sluice gate lowers into the chasm, the southern passage seals.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_11",
        "type": "signpost",
        "x": 3,
        "y": 2,
        "z": 0,
        "title": "Architect's Note #11",
        "text": "The master valve is balanced upon a counterweight: as the northern sluice gate lowers into the chasm, the southern passage seals.",
        "style": "stone_tablet"
      },
      {
        "id": "lever_11",
        "type": "lever",
        "name": "Counterweight Sluice Lever",
        "style": "switch_lever",
        "x": 2,
        "y": 4,
        "elevation": 0,
        "state": false,
        "targets": [
          {
            "action": "toggle_tile",
            "layer": "ground",
            "x": 8,
            "y": 3,
            "stateA": 0,
            "stateB": 1
          },
          {
            "action": "toggle_tile",
            "layer": "ground",
            "x": 3,
            "y": 5,
            "stateA": 1,
            "stateB": 0
          }
        ]
      },
      {
        "id": "key_gold_11",
        "type": "key",
        "color": "#fbbf24",
        "name": "Sluice Key",
        "x": 14,
        "y": 3,
        "elevation": 0
      },
      {
        "id": "door_gold_11",
        "type": "door",
        "requiresKey": "key_gold_11",
        "color": "#fbbf24",
        "name": "Gear Crypt Gate",
        "x": 13,
        "y": 10,
        "elevation": 0
      },
      {
        "id": "wall_decor_11",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "Lower the northern sluice to claim the gilded key.",
        "playerDialogue": "The northern gate opened, allowing passage to the eastern vault.",
        "x": 2,
        "y": 3,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "12",
    "chapter": "chapter_3",
    "zone": "zone_3",
    "title": "Master of Wheels",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 19,
      "height": 17
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "temple"
    },
    "spawn": {
      "x": 9,
      "y": 2,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 9,
      "y": 14,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 55,
    "parTime": 33,
    "architectNote": "The entire citadel moves in harmony. Retrieve the Ruby Key from the western furnace, activate the eastern dynamo, and claim the Master Gear.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_12",
        "type": "signpost",
        "x": 10,
        "y": 2,
        "z": 0,
        "title": "Architect's Note #12",
        "text": "The entire citadel moves in harmony. Retrieve the Ruby Key from the western furnace, activate the eastern dynamo, and claim the Master Gear.",
        "style": "stone_tablet"
      },
      {
        "id": "key_ruby_12",
        "type": "key",
        "color": "#ef4444",
        "name": "Furnace Ruby Key",
        "x": 2,
        "y": 8,
        "elevation": 0
      },
      {
        "id": "lever_12",
        "type": "lever",
        "name": "Master Dynamo Lever",
        "style": "switch_lever",
        "x": 16,
        "y": 8,
        "elevation": 0,
        "state": false,
        "targets": [
          {
            "action": "toggle_tile",
            "layer": "ground",
            "x": 9,
            "y": 12,
            "stateA": 0,
            "stateB": 1
          }
        ]
      },
      {
        "id": "door_ruby_12",
        "type": "door",
        "requiresKey": "key_ruby_12",
        "color": "#ef4444",
        "name": "Apex Portcullis",
        "x": 9,
        "y": 13,
        "elevation": 0
      },
      {
        "id": "wall_decor_12",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "The Triad of the Machine: West yields the key, East drops the wall, South crowns the Master.",
        "playerDialogue": "Both the Ruby Key and the Dynamo Switch are required to enter the Apex.",
        "x": 9,
        "y": 6,
        "elevation": 0
      },
      {
        "id": "gem_clockwork_12",
        "type": "collectible",
        "collectibleType": "gem",
        "name": "Master Chronometer",
        "scoreValue": 300,
        "x": 9,
        "y": 8,
        "elevation": 0
      }
    ]
  }
]);
