/**
 * Casual Maze Game - Campaign Chapter 5 Levels
 */

export const CAMPAIGN_CH5_LEVELS = Object.freeze([
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "17",
    "chapter": "chapter_5",
    "zone": "zone_5",
    "title": "The Fire Vents",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 15,
      "height": 13
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "lava"
    },
    "spawn": {
      "x": 2,
      "y": 2,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 12,
      "y": 10,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 22,
    "parTime": 14,
    "architectNote": "Feel the rhythmic pulse of the caldera. Time your movement through the basalt corridors and harbor in the alcoves.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          1,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          1,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_17",
        "type": "signpost",
        "x": 3,
        "y": 2,
        "z": 0,
        "title": "Architect's Note #17",
        "text": "Feel the rhythmic pulse of the caldera. Time your movement through the basalt corridors and harbor in the alcoves.",
        "style": "stone_tablet"
      },
      {
        "id": "hazard_vent_17_a",
        "type": "hazard",
        "style": "fire_jet",
        "name": "Magma Vent Alpha",
        "interval": 3,
        "activeDuration": 1.2,
        "initialOffset": 0,
        "x": 7,
        "y": 6,
        "elevation": 0,
        "z": 0
      },
      {
        "id": "hazard_vent_17_b",
        "type": "hazard",
        "style": "fire_jet",
        "name": "Magma Vent Beta",
        "interval": 3,
        "activeDuration": 1.2,
        "initialOffset": 1.5,
        "x": 8,
        "y": 6,
        "elevation": 0,
        "z": 0
      },
      {
        "id": "gem_fire_opal_17",
        "type": "collectible",
        "collectibleType": "gem",
        "name": "Fire Opal",
        "scoreValue": 150,
        "x": 7,
        "y": 2,
        "elevation": 0
      },
      {
        "id": "wall_note_17",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "Ancient miners carved niches into the basalt to shelter from flame bursts.",
        "playerDialogue": "The vents pulse periodically. I can harbor in the side niches.",
        "x": 2,
        "y": 1,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "18",
    "chapter": "chapter_5",
    "zone": "zone_5",
    "title": "The Molten Sentinels",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 17,
      "height": 15
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "lava"
    },
    "spawn": {
      "x": 2,
      "y": 2,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 15,
      "y": 12,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 35,
    "parTime": 21,
    "architectNote": "Obsidian golems patrol the basalt halls in eternal vigilance. Lure them around the central pillars to slip past.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_18",
        "type": "signpost",
        "x": 3,
        "y": 2,
        "z": 0,
        "title": "Architect's Note #18",
        "text": "Obsidian golems patrol the basalt halls in eternal vigilance. Lure them around the central pillars to slip past.",
        "style": "stone_tablet"
      },
      {
        "id": "patroller_18",
        "type": "patroller",
        "name": "Molten Sentinel",
        "speed": 1,
        "waypoints": [
          {
            "x": 6,
            "y": 5,
            "z": 0
          },
          {
            "x": 10,
            "y": 5,
            "z": 0
          },
          {
            "x": 10,
            "y": 9,
            "z": 0
          },
          {
            "x": 6,
            "y": 9,
            "z": 0
          }
        ]
      },
      {
        "id": "key_bronze_18",
        "type": "key",
        "color": "#f97316",
        "name": "Basalt Foundry Key",
        "x": 14,
        "y": 2,
        "elevation": 0
      },
      {
        "id": "door_bronze_18",
        "type": "door",
        "requiresKey": "key_bronze_18",
        "color": "#f97316",
        "name": "Foundry Vault Gate",
        "x": 13,
        "y": 11,
        "elevation": 0
      },
      {
        "id": "wall_note_18",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "Forged from living magma and black glass, the sentinels follow their endless circuit.",
        "playerDialogue": "If I circle the central pillar, the sentinel will pace ahead of me.",
        "x": 2,
        "y": 1,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "19",
    "chapter": "chapter_5",
    "zone": "zone_5",
    "title": "The Crucible Crossing",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 19,
      "height": 15
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "lava"
    },
    "spawn": {
      "x": 2,
      "y": 7,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 16,
      "y": 7,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 29,
    "parTime": 18,
    "architectNote": "The crucible combines searing flame jets with a vigilant sentinel. Activate the cool crystal beacon midway to secure your footing.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_19",
        "type": "signpost",
        "x": 3,
        "y": 7,
        "z": 0,
        "title": "Architect's Note #19",
        "text": "The crucible combines searing flame jets with a vigilant sentinel. Activate the cool crystal beacon midway to secure your footing.",
        "style": "stone_tablet"
      },
      {
        "id": "checkpoint_19",
        "type": "checkpoint",
        "name": "Glacial Beacon",
        "x": 9,
        "y": 7,
        "elevation": 0,
        "z": 0
      },
      {
        "id": "hazard_vent_19",
        "type": "hazard",
        "style": "fire_jet",
        "name": "Crucible Vent",
        "interval": 3.5,
        "activeDuration": 1,
        "initialOffset": 0.5,
        "x": 6,
        "y": 7,
        "elevation": 0,
        "z": 0
      },
      {
        "id": "patroller_19",
        "type": "patroller",
        "name": "Crucible Guardian",
        "speed": 1,
        "waypoints": [
          {
            "x": 6,
            "y": 4,
            "z": 0
          },
          {
            "x": 12,
            "y": 4,
            "z": 0
          }
        ]
      },
      {
        "id": "key_silver_19",
        "type": "key",
        "color": "#e2e8f0",
        "name": "Crucible Silver Key",
        "x": 9,
        "y": 2,
        "elevation": 0
      },
      {
        "id": "door_silver_19",
        "type": "door",
        "requiresKey": "key_silver_19",
        "color": "#e2e8f0",
        "name": "Sanctum Silver Seal",
        "x": 14,
        "y": 7,
        "elevation": 0
      },
      {
        "id": "wall_note_19",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "The glacial beacon radiates soothing chill amidst the roaring forge.",
        "playerDialogue": "Activating the checkpoint will save my position if I stumble.",
        "x": 2,
        "y": 6,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "20",
    "chapter": "chapter_5",
    "zone": "zone_5",
    "title": "The Caldera Gauntlet",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 21,
      "height": 19
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "lava"
    },
    "spawn": {
      "x": 2,
      "y": 9,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 18,
      "y": 9,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 36,
    "parTime": 22,
    "architectNote": "Here in the heart of Mount Ignis, all trials converge: synchronized fire jets, dual sentinels, and the royal Caldera Key. Prove your mastery.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_20",
        "type": "signpost",
        "x": 3,
        "y": 9,
        "z": 0,
        "title": "Architect's Note #20",
        "text": "Here in the heart of Mount Ignis, all trials converge: synchronized fire jets, dual sentinels, and the royal Caldera Key. Prove your mastery.",
        "style": "stone_tablet"
      },
      {
        "id": "checkpoint_20",
        "type": "checkpoint",
        "name": "Heart of the Forge Beacon",
        "x": 10,
        "y": 9,
        "elevation": 0,
        "z": 0
      },
      {
        "id": "patroller_20_north",
        "type": "patroller",
        "name": "North Foundry Sentinel",
        "speed": 1,
        "waypoints": [
          {
            "x": 13,
            "y": 4,
            "z": 0
          },
          {
            "x": 7,
            "y": 4,
            "z": 0
          }
        ]
      },
      {
        "id": "patroller_20_south",
        "type": "patroller",
        "name": "South Foundry Sentinel",
        "speed": 1,
        "waypoints": [
          {
            "x": 7,
            "y": 16,
            "z": 0
          },
          {
            "x": 13,
            "y": 16,
            "z": 0
          }
        ]
      },
      {
        "id": "hazard_vent_20_a",
        "type": "hazard",
        "style": "fire_jet",
        "name": "Crucible Jet Alpha",
        "interval": 3,
        "activeDuration": 1,
        "initialOffset": 0,
        "x": 8,
        "y": 9,
        "elevation": 0,
        "z": 0
      },
      {
        "id": "hazard_vent_20_b",
        "type": "hazard",
        "style": "fire_jet",
        "name": "Crucible Jet Beta",
        "interval": 3,
        "activeDuration": 1,
        "initialOffset": 1.5,
        "x": 12,
        "y": 9,
        "elevation": 0,
        "z": 0
      },
      {
        "id": "key_ruby_20",
        "type": "key",
        "color": "#ef4444",
        "name": "Caldera Ruby Key",
        "x": 10,
        "y": 2,
        "elevation": 0
      },
      {
        "id": "door_ruby_20",
        "type": "door",
        "requiresKey": "key_ruby_20",
        "color": "#ef4444",
        "name": "Apex Crucible Gate",
        "x": 15,
        "y": 9,
        "elevation": 0
      },
      {
        "id": "wall_note_20",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "The Sovereign Forge—where legendary relics were tempered in primeval dragon fire.",
        "playerDialogue": "Both sentinels pace the galleries. I must time my ascent to the North Gallery.",
        "x": 2,
        "y": 8,
        "elevation": 0
      }
    ]
  }
]);
