/**
 * Casual Maze Game - Campaign Chapter 6 Levels
 */

export const CAMPAIGN_CH6_LEVELS = Object.freeze([
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "21",
    "chapter": "chapter_6",
    "zone": "zone_6",
    "title": "The Rune Lock",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 15,
      "height": 13
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "sunset"
    },
    "spawn": {
      "x": 2,
      "y": 2,
      "elevation": 0,
      "style": "stairs_down",
      "wallDirection": "none"
    },
    "exit": {
      "x": 12,
      "y": 10,
      "elevation": 0,
      "style": "portal",
      "wallDirection": "none"
    },
    "parSteps": 22,
    "parTime": 14,
    "architectNote": "The ancient gate is bound by arcane runes. Recall the celestial sequence to dispel the barrier.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_21",
        "type": "signpost",
        "x": 3,
        "y": 2,
        "z": 0,
        "title": "Architect's Note #21",
        "text": "The ancient gate is bound by arcane runes. Recall the celestial sequence to dispel the barrier.",
        "style": "astral_scroll"
      },
      {
        "id": "puzzle_gate_21",
        "type": "puzzle_gate",
        "x": 6,
        "y": 6,
        "z": 0,
        "puzzleType": "rune_memory",
        "solution": [
          0,
          2,
          1,
          3
        ],
        "name": "Arcane Rune Seal"
      },
      {
        "id": "gem_astral_21",
        "type": "collectible",
        "collectibleType": "gem",
        "name": "Sunset Amethyst",
        "scoreValue": 150,
        "x": 12,
        "y": 2,
        "elevation": 0
      },
      {
        "id": "wall_note_21",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "The memory of the stars is written in glyphs of light upon the stone.",
        "playerDialogue": "Touching the runes reveals their sequence. I must memorize the order.",
        "x": 2,
        "y": 1,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "22",
    "chapter": "chapter_6",
    "zone": "zone_6",
    "title": "The Cipher Dials",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 17,
      "height": 15
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "sunset"
    },
    "spawn": {
      "x": 2,
      "y": 2,
      "elevation": 0,
      "style": "stairs_down",
      "wallDirection": "none"
    },
    "exit": {
      "x": 14,
      "y": 12,
      "elevation": 0,
      "style": "portal",
      "wallDirection": "none"
    },
    "parSteps": 38,
    "parTime": 23,
    "architectNote": "Align the stellar dials according to the celestial dance: first the Sun, second the Moon, third the Horizon.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_22",
        "type": "signpost",
        "x": 3,
        "y": 2,
        "z": 0,
        "title": "Architect's Note #22",
        "text": "Align the stellar dials according to the celestial dance: first the Sun, second the Moon, third the Horizon.",
        "style": "astral_scroll"
      },
      {
        "id": "puzzle_gate_22",
        "type": "puzzle_gate",
        "x": 7,
        "y": 7,
        "z": 0,
        "puzzleType": "cipher_dial",
        "solution": [
          0,
          1,
          2
        ],
        "name": "Stellar Cipher Dial"
      },
      {
        "id": "key_azure_22",
        "type": "key",
        "color": "#38bdf8",
        "name": "Azure Star Key",
        "x": 14,
        "y": 2,
        "elevation": 0
      },
      {
        "id": "door_azure_22",
        "type": "door",
        "requiresKey": "key_azure_22",
        "color": "#38bdf8",
        "name": "Azure Astral Gate",
        "x": 14,
        "y": 9,
        "elevation": 0
      },
      {
        "id": "wall_decor_22_sun",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "The Solar Crest shines first at dawn: ☀️ Sun.",
        "playerDialogue": "The first ring must be turned to the Sun.",
        "x": 4,
        "y": 1,
        "elevation": 0
      },
      {
        "id": "wall_decor_22_moon",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "The Lunar Crescent wanes second at dusk: 🌙 Moon.",
        "playerDialogue": "The second ring aligns to the Moon.",
        "x": 5,
        "y": 1,
        "elevation": 0
      },
      {
        "id": "wall_decor_22_horizon",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "The Horizon unites heaven and earth at twilight: 🌅 Horizon.",
        "playerDialogue": "The third ring rests upon the Horizon.",
        "x": 6,
        "y": 1,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "23",
    "chapter": "chapter_6",
    "zone": "zone_6",
    "title": "The Entangled Wards",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 19,
      "height": 15
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "sunset"
    },
    "spawn": {
      "x": 2,
      "y": 7,
      "elevation": 0,
      "style": "stairs_down",
      "wallDirection": "none"
    },
    "exit": {
      "x": 17,
      "y": 7,
      "elevation": 0,
      "style": "portal",
      "wallDirection": "none"
    },
    "parSteps": 30,
    "parTime": 18,
    "architectNote": "The dual seals are entangled. Break the rune ward to access the Dynamo Lever, lowering the barrier to the Cipher Sanctum.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_23",
        "type": "signpost",
        "x": 3,
        "y": 7,
        "z": 0,
        "title": "Architect's Note #23",
        "text": "The dual seals are entangled. Break the rune ward to access the Dynamo Lever, lowering the barrier to the Cipher Sanctum.",
        "style": "astral_scroll"
      },
      {
        "id": "puzzle_gate_23_rune",
        "type": "puzzle_gate",
        "x": 6,
        "y": 7,
        "z": 0,
        "puzzleType": "rune_memory",
        "solution": [
          2,
          0,
          3,
          1
        ],
        "name": "Outer Rune Ward"
      },
      {
        "id": "lever_23",
        "type": "lever",
        "name": "Dynamo Conduit Lever",
        "style": "switch_lever",
        "x": 9,
        "y": 2,
        "elevation": 0,
        "state": false,
        "targets": [
          {
            "action": "toggle_tile",
            "layer": "ground",
            "x": 12,
            "y": 7,
            "stateA": 0,
            "stateB": 1
          }
        ]
      },
      {
        "id": "puzzle_gate_23_cipher",
        "type": "puzzle_gate",
        "x": 14,
        "y": 7,
        "z": 0,
        "puzzleType": "cipher_dial",
        "solution": [
          2,
          1,
          3
        ],
        "name": "Inner Cipher Ward"
      },
      {
        "id": "wall_note_23",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "The celestial ward alignment: 🌅 Horizon first, 🌙 Moon second, and ⭐ Star third.",
        "playerDialogue": "The inner cipher dials require Horizon, Moon, and Star.",
        "x": 2,
        "y": 6,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "24",
    "chapter": "chapter_6",
    "zone": "zone_6",
    "title": "The Grand Archive",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 21,
      "height": 19
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "sunset"
    },
    "spawn": {
      "x": 2,
      "y": 9,
      "elevation": 0,
      "style": "stairs_down",
      "wallDirection": "none"
    },
    "exit": {
      "x": 18,
      "y": 9,
      "elevation": 0,
      "style": "portal",
      "wallDirection": "none"
    },
    "parSteps": 52,
    "parTime": 32,
    "architectNote": "The Grand Archive holds the accumulated wisdom of all celestial trials. Decipher the rune script, align the stargazer cipher, and claim the Master Golden Key.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_24",
        "type": "signpost",
        "x": 3,
        "y": 9,
        "z": 0,
        "title": "Architect's Note #24",
        "text": "The Grand Archive holds the accumulated wisdom of all celestial trials. Decipher the rune script, align the stargazer cipher, and claim the Master Golden Key.",
        "style": "astral_scroll"
      },
      {
        "id": "puzzle_gate_24_rune",
        "type": "puzzle_gate",
        "x": 10,
        "y": 4,
        "z": 0,
        "puzzleType": "rune_memory",
        "solution": [
          0,
          3,
          1,
          2
        ],
        "name": "Scriptorium Rune Seal"
      },
      {
        "id": "key_gold_24",
        "type": "key",
        "color": "#fbbf24",
        "name": "Master Archive Key",
        "x": 10,
        "y": 2,
        "elevation": 0
      },
      {
        "id": "puzzle_gate_24_cipher",
        "type": "puzzle_gate",
        "x": 10,
        "y": 14,
        "z": 0,
        "puzzleType": "cipher_dial",
        "solution": [
          3,
          1,
          2
        ],
        "name": "Stargazer Cipher Dial"
      },
      {
        "id": "lever_24_archive",
        "type": "lever",
        "name": "Stargazer Dynamo Lever",
        "style": "switch_lever",
        "x": 10,
        "y": 16,
        "elevation": 0,
        "state": false,
        "targets": [
          {
            "action": "toggle_tile",
            "layer": "ground",
            "x": 16,
            "y": 9,
            "stateA": 0,
            "stateB": 1
          }
        ]
      },
      {
        "id": "door_gold_24",
        "type": "door",
        "requiresKey": "key_gold_24",
        "color": "#fbbf24",
        "name": "Grand Archive Golden Gate",
        "x": 15,
        "y": 9,
        "elevation": 0
      },
      {
        "id": "wall_note_24",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "The Stargazer's creed inscribed on stone: ⭐ Star first, 🌙 Moon second, 🌅 Horizon third.",
        "playerDialogue": "The south cipher dials must be set to Star, Moon, and Horizon.",
        "x": 2,
        "y": 8,
        "elevation": 0
      }
    ]
  }
]);
