/**
 * Casual Maze Game - Campaign Chapter 8 Levels
 */

export const CAMPAIGN_CH8_LEVELS = Object.freeze([
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "29",
    "chapter": "chapter_8",
    "zone": "zone_8",
    "title": "The Cardinal Needle",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 15,
      "height": 15
    },
    "config": {
      "fogOfWar": true,
      "viewRadius": 6,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "dungeon",
      "viewPerspective": "angled"
    },
    "spawn": {
      "x": 1,
      "y": 1,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 13,
      "y": 13,
      "elevation": 0,
      "style": "portal",
      "label": "Needle Sanctum"
    },
    "parSteps": 48,
    "parTime": 30,
    "architectNote": "Rotate the camera [Q / R] to view the cardinal corridors. Seek the golden key in the south-west wing.",
    "help": {
      "title": "Level 29: The Cardinal Needle",
      "message": "Press [Q] and [R] to rotate the view. Screen controls adapt automatically to your camera heading."
    },
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ]
    },
    "entities": [
      {
        "id": "key_gold_29",
        "type": "key",
        "color": "#fbbf24",
        "name": "Golden Needle Key",
        "x": 1,
        "y": 13,
        "elevation": 0
      },
      {
        "id": "door_gold_29",
        "type": "door",
        "color": "#fbbf24",
        "name": "Needle Sanctum Gate",
        "requiresKey": "key_gold_29",
        "x": 12,
        "y": 13,
        "elevation": 0
      },
      {
        "id": "checkpoint_29",
        "type": "checkpoint",
        "style": "crystal_beacon",
        "name": "Central Needle Shrine",
        "x": 7,
        "y": 5,
        "elevation": 0,
        "color": "#38bdf8"
      },
      {
        "id": "decor_note_north",
        "type": "wall_decor",
        "decorType": "note",
        "title": "Needle Alignment",
        "text": "Rotating 90 degrees CCW [Q] turns East to facing up. Screen movement always follows your view.",
        "author": "Guild Cartographer",
        "x": 7,
        "y": 1,
        "facing": "south",
        "elevation": 0
      },
      {
        "id": "decor_carving_center",
        "type": "wall_decor",
        "decorType": "carving",
        "title": "Four Faces of the Monolith",
        "text": "The monolith casts its shadow according to the observer angle.",
        "author": "Ancient Stonemason",
        "x": 7,
        "y": 9,
        "facing": "north",
        "elevation": 0
      },
      {
        "id": "gem_score_29a",
        "type": "collectible",
        "collectibleType": "gem",
        "name": "Sapphire Prism",
        "scoreValue": 150,
        "color": "#38bdf8",
        "x": 13,
        "y": 1,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "30",
    "chapter": "chapter_8",
    "zone": "zone_8",
    "title": "The Hidden Underpass",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 15,
      "height": 15
    },
    "config": {
      "fogOfWar": true,
      "viewRadius": 6,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "dungeon",
      "viewPerspective": "angled"
    },
    "spawn": {
      "x": 1,
      "y": 1,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 13,
      "y": 13,
      "elevation": 0,
      "style": "portal",
      "label": "Overpass Gate"
    },
    "parSteps": 54,
    "parTime": 36,
    "architectNote": "Overhead bridges occlude low ground corridors. Rotate 90 degrees to peer straight through underpass tunnels!",
    "help": {
      "title": "Level 30: The Hidden Underpass",
      "message": "Notice how rotation changes which side of bridges and walls you see. The tunnel key lies under the span."
    },
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          "R_S",
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          "R_N",
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_NS",
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_NS",
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_NS",
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_NS",
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_NS",
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_NS",
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_NS",
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ]
    },
    "entities": [
      {
        "id": "key_cyan_30",
        "type": "key",
        "color": "#06b6d4",
        "name": "Underpass Key",
        "x": 7,
        "y": 7,
        "elevation": 0
      },
      {
        "id": "door_cyan_30",
        "type": "door",
        "color": "#06b6d4",
        "name": "Underpass Exit Gate",
        "requiresKey": "key_cyan_30",
        "x": 12,
        "y": 13,
        "elevation": 0
      },
      {
        "id": "decor_note_bridge",
        "type": "wall_decor",
        "decorType": "note",
        "title": "Bridge Observation",
        "text": "Rotating [Q / R] shifts the 2.5D perspective, revealing what was hidden behind elevated bridge spans.",
        "author": "Bridge Engineer",
        "x": 5,
        "y": 1,
        "facing": "south",
        "elevation": 0
      },
      {
        "id": "gem_bridge_top",
        "type": "collectible",
        "collectibleType": "gem",
        "name": "Skyward Topaz",
        "scoreValue": 200,
        "color": "#fbbf24",
        "x": 7,
        "y": 7,
        "elevation": 1
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "31",
    "chapter": "chapter_8",
    "zone": "zone_8",
    "title": "The Four-Faced Pillar",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 15,
      "height": 15
    },
    "config": {
      "fogOfWar": true,
      "viewRadius": 6,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "temple",
      "viewPerspective": "angled"
    },
    "spawn": {
      "x": 1,
      "y": 1,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 13,
      "y": 13,
      "elevation": 0,
      "style": "portal",
      "label": "Sanctuary of the Four Winds"
    },
    "parSteps": 58,
    "parTime": 38,
    "architectNote": "Four faces of the monolith tell one story. Walk the perimeter and rotate the view to read each inscription.",
    "help": {
      "title": "Level 31: The Four-Faced Pillar",
      "message": "Rotate the camera to view each side of the central monument. Find the ruby key in the eastern corner."
    },
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ]
    },
    "entities": [
      {
        "id": "key_ruby_31",
        "type": "key",
        "color": "#f43f5e",
        "name": "Ruby Monolith Key",
        "x": 13,
        "y": 2,
        "elevation": 0
      },
      {
        "id": "door_ruby_31",
        "type": "door",
        "color": "#f43f5e",
        "name": "Southern Pillar Gate",
        "requiresKey": "key_ruby_31",
        "x": 12,
        "y": 13,
        "elevation": 0
      },
      {
        "id": "decor_north_face",
        "type": "wall_decor",
        "decorType": "carving",
        "title": "North Face of Monolith",
        "text": "Face of the North Wind: The ruby key sleeps in the eastern vault.",
        "author": "Ancient Scribe",
        "x": 7,
        "y": 6,
        "facing": "north",
        "elevation": 0
      },
      {
        "id": "decor_east_face",
        "type": "wall_decor",
        "decorType": "carving",
        "title": "East Face of Monolith",
        "text": "Face of the Dawn: When the perspective is turned, unseen paths emerge.",
        "author": "Ancient Scribe",
        "x": 8,
        "y": 7,
        "facing": "east",
        "elevation": 0
      },
      {
        "id": "decor_south_face",
        "type": "wall_decor",
        "decorType": "carving",
        "title": "South Face of Monolith",
        "text": "Face of the Zenith: Unlock the southern portal to continue upward.",
        "author": "Ancient Scribe",
        "x": 7,
        "y": 8,
        "facing": "south",
        "elevation": 0
      },
      {
        "id": "decor_west_face",
        "type": "wall_decor",
        "decorType": "carving",
        "title": "West Face of Monolith",
        "text": "Face of the Dusk: Rotate [R] clockwise to survey the courtyard.",
        "author": "Ancient Scribe",
        "x": 6,
        "y": 7,
        "facing": "west",
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "32",
    "chapter": "chapter_8",
    "zone": "zone_8",
    "title": "The Prismatic Spire",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 17,
      "height": 17
    },
    "config": {
      "fogOfWar": true,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "snow",
      "viewPerspective": "angled"
    },
    "spawn": {
      "x": 1,
      "y": 1,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 15,
      "y": 15,
      "elevation": 0,
      "style": "portal",
      "label": "Crown of the Monolith",
      "targetLevel": "1"
    },
    "exits": [
      {
        "id": "exit_spire_primary",
        "x": 15,
        "y": 15,
        "elevation": 0,
        "style": "portal",
        "label": "Crown of the Monolith",
        "targetLevel": "1"
      },
      {
        "id": "exit_spire_citadel_branch",
        "x": 1,
        "y": 15,
        "elevation": 0,
        "style": "stairs",
        "label": "Descend to Whispering Citadel",
        "targetLevel": "story_citadel_1"
      }
    ],
    "parSteps": 72,
    "parTime": 46,
    "architectNote": "At the apex of the monolith, two distinct routes await: return victorious to the Grand Hub, or branch downward into the Whispering Citadel.",
    "help": {
      "title": "Level 32: The Prismatic Spire",
      "message": "Explore the peak! Multiple exits offer choice: complete the campaign or embark on the Whispering Citadel story quest."
    },
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          "R_E",
          0,
          0,
          0,
          0,
          0,
          "R_W",
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          "B_EW",
          "B_EW",
          "B_EW",
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ]
    },
    "entities": [
      {
        "id": "key_emerald_32",
        "type": "key",
        "color": "#10b981",
        "name": "Spire Apex Key",
        "x": 15,
        "y": 1,
        "elevation": 0
      },
      {
        "id": "door_emerald_32",
        "type": "door",
        "color": "#10b981",
        "name": "Crown Barrier",
        "requiresKey": "key_emerald_32",
        "x": 15,
        "y": 14,
        "elevation": 0
      },
      {
        "id": "checkpoint_32",
        "type": "checkpoint",
        "style": "shrine",
        "name": "Spire Sanctuary Waypoint",
        "x": 8,
        "y": 8,
        "elevation": 1,
        "color": "#38bdf8"
      },
      {
        "id": "gem_apex_crown",
        "type": "collectible",
        "collectibleType": "gem",
        "name": "Diamond of the Monolith",
        "scoreValue": 500,
        "color": "#ffffff",
        "x": 8,
        "y": 2,
        "elevation": 0
      }
    ]
  }
]);
