/**
 * Casual Maze Game - Campaign Chapter 2 Levels
 */

export const CAMPAIGN_CH2_LEVELS = Object.freeze([
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "5",
    "chapter": "chapter_2",
    "zone": "zone_2",
    "title": "The Canopy Bridge",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 15,
      "height": 13
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "jungle"
    },
    "spawn": {
      "x": 2,
      "y": 11,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 12,
      "y": 4,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 26,
    "parTime": 16,
    "architectNote": "Look up! The jungle canopy offers high paths. Ascend the wooden incline to claim the Canopy Key.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          "R_S",
          1,
          1,
          1,
          1,
          0,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          "R_N",
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_5",
        "type": "signpost",
        "x": 3,
        "y": 11,
        "z": 0,
        "title": "Architect's Note #5",
        "text": "Look up! The jungle canopy offers high paths. Ascend the wooden incline to claim the Canopy Key.",
        "style": "wooden_sign"
      },
      {
        "id": "key_jungle_5",
        "type": "key",
        "x": 7,
        "y": 6,
        "z": 1,
        "elevation": 1,
        "color": "#34d399",
        "name": "Canopy Key",
        "style": "ornate",
        "glowEffect": "vibrant"
      },
      {
        "id": "door_jungle_5",
        "type": "door",
        "x": 12,
        "y": 3,
        "requiresKey": "key_jungle_5",
        "color": "#34d399",
        "style": "portcullis",
        "orientation": "horizontal"
      },
      {
        "id": "inscr_canopy_5",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "Ancient glyph: The high wooden trestle leads to the canopy overlook. Above, the canopy key rests among the vines.",
        "playerDialogue": "The high bridge deck is the only way to reach the Canopy Key.",
        "x": 2,
        "y": 10,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "6",
    "chapter": "chapter_2",
    "zone": "zone_2",
    "title": "Canopy Crossings",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 17,
      "height": 15
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "jungle"
    },
    "spawn": {
      "x": 2,
      "y": 7,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 15,
      "y": 2,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 48,
    "parTime": 29,
    "architectNote": "A single bridge can be traversed twice: once as a cool tunnel beneath, and once as a soaring walk above.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          "R_S",
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          "R_N",
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_6",
        "type": "signpost",
        "x": 3,
        "y": 7,
        "z": 0,
        "title": "Architect's Note #6",
        "text": "A single bridge can be traversed twice: once as a cool tunnel beneath, and once as a soaring walk above.",
        "style": "wooden_sign"
      },
      {
        "id": "key_amber_6",
        "type": "key",
        "x": 14,
        "y": 12,
        "color": "#f59e0b",
        "name": "Amber Key",
        "style": "ornate"
      },
      {
        "id": "door_amber_6",
        "type": "door",
        "x": 9,
        "y": 12,
        "requiresKey": "key_amber_6",
        "color": "#f59e0b",
        "style": "portcullis",
        "orientation": "vertical"
      },
      {
        "id": "key_emerald_6",
        "type": "key",
        "x": 8,
        "y": 7,
        "z": 1,
        "elevation": 1,
        "color": "#34d399",
        "name": "Canopy Key",
        "style": "ornate",
        "glowEffect": "vibrant"
      },
      {
        "id": "door_emerald_6",
        "type": "door",
        "x": 14,
        "y": 2,
        "requiresKey": "key_emerald_6",
        "color": "#34d399",
        "style": "portcullis",
        "orientation": "vertical"
      },
      {
        "id": "inscr_tunnel_6",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "Runic tablet: Ground below, heavens above. Walk the underpass tunnel first, then ascend to cross the bridge deck.",
        "playerDialogue": "Underpass first for the Amber Key, then overhead bridge for the Canopy Key.",
        "x": 3,
        "y": 8,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "7",
    "chapter": "chapter_2",
    "zone": "zone_2",
    "title": "The Sunken Chasm",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 17,
      "height": 15
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 7,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "jungle"
    },
    "spawn": {
      "x": 2,
      "y": 5,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 8,
      "y": 1,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 45,
    "parTime": 27,
    "architectNote": "Where canopies collide, paths weave over and under. Mind your footing and explore both layers.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          0,
          0,
          "R_E",
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          "R_W",
          0,
          0,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          "R_S",
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          "R_N",
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          "B_NS",
          "B_NS",
          "B_NS",
          "B_NS",
          "B_NS",
          "B_NS",
          "B_NS",
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_7",
        "type": "signpost",
        "x": 3,
        "y": 5,
        "z": 0,
        "title": "Architect's Note #7",
        "text": "Where canopies collide, paths weave over and under. Mind your footing and explore both layers.",
        "style": "wooden_sign"
      },
      {
        "id": "key_azure_7",
        "type": "key",
        "x": 14,
        "y": 9,
        "z": 1,
        "elevation": 1,
        "color": "#06b6d4",
        "name": "Azure Canopy Key",
        "style": "ornate",
        "glowEffect": "vibrant"
      },
      {
        "id": "door_azure_7",
        "type": "door",
        "x": 8,
        "y": 3,
        "requiresKey": "key_azure_7",
        "color": "#06b6d4",
        "style": "portcullis",
        "orientation": "horizontal"
      },
      {
        "id": "inscr_chasm_7",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "Ancient stone: Two bridges intersect across the chasm depths. Mind the directional incline.",
        "playerDialogue": "The perpendicular bridges weave across two distinct elevations.",
        "x": 3,
        "y": 4,
        "elevation": 0
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "8",
    "chapter": "chapter_2",
    "zone": "zone_2",
    "title": "Citadel of the Two Horizons",
    "author": "Inbar Rose",
    "version": 1,
    "dimensions": {
      "width": 19,
      "height": 17
    },
    "config": {
      "fogOfWar": false,
      "viewRadius": 8,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "jungle"
    },
    "spawn": {
      "x": 9,
      "y": 8,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 9,
      "y": 2,
      "elevation": 0,
      "style": "portal"
    },
    "parSteps": 68,
    "parTime": 41,
    "architectNote": "Twin bridges frame the Horizon Citadel. Master both crossings to unseal the apex altar.",
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          "R_S",
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          "R_S",
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1
        ],
        [
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1
        ],
        [
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1
        ],
        [
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1
        ],
        [
          1,
          1,
          0,
          1,
          1,
          "R_N",
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          "R_N",
          1,
          1,
          0,
          1,
          1
        ],
        [
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "sign_arch_8",
        "type": "signpost",
        "x": 9,
        "y": 7,
        "z": 0,
        "title": "Architect's Note #8",
        "text": "Twin bridges frame the Horizon Citadel. Master both crossings to unseal the apex altar.",
        "style": "wooden_sign"
      },
      {
        "id": "key_ruby_8",
        "type": "key",
        "x": 5,
        "y": 8,
        "z": 1,
        "elevation": 1,
        "color": "#ef4444",
        "name": "Ruby Horizon Key",
        "style": "ornate",
        "glowEffect": "vibrant"
      },
      {
        "id": "door_ruby_8",
        "type": "door",
        "x": 12,
        "y": 8,
        "requiresKey": "key_ruby_8",
        "color": "#ef4444",
        "style": "portcullis",
        "orientation": "vertical"
      },
      {
        "id": "key_gold_8",
        "type": "key",
        "x": 13,
        "y": 8,
        "z": 1,
        "elevation": 1,
        "color": "#eab308",
        "name": "Gilded Horizon Key",
        "style": "ornate",
        "glowEffect": "vibrant"
      },
      {
        "id": "door_gold_8",
        "type": "door",
        "x": 10,
        "y": 3,
        "requiresKey": "key_gold_8",
        "color": "#eab308",
        "style": "portcullis",
        "orientation": "vertical"
      },
      {
        "id": "inscr_citadel_8",
        "type": "wall_decor",
        "decorType": "carving",
        "text": "Citadel inscription: The twin bridges guard the eastern and western horizons. Unlock both to reveal the apex stairs.",
        "playerDialogue": "Twin bridges flanking the central courtyard—both keys are strictly required.",
        "x": 8,
        "y": 7,
        "elevation": 0
      }
    ]
  }
]);
