/**
 * Casual Maze Game - Tutorial Levels
 */

export const TUTORIAL_LEVELS = Object.freeze([
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "tutorial_1",
    "title": "First Steps",
    "author": "Casual Maze Academy",
    "version": 1,
    "dimensions": {
      "width": 9,
      "height": 9
    },
    "config": {
      "fogOfWar": false,
      "mapRevealed": true,
      "viewRadius": 6,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "dungeon"
    },
    "help": {
      "title": "Navigation Basics",
      "message": "Welcome to Casual Maze! Use WASD or Arrow Keys to navigate through the corridor and reach the glowing blue exit portal."
    },
    "spawn": {
      "x": 1,
      "y": 1,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 7,
      "y": 7,
      "style": "archway"
    },
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": []
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "tutorial_2",
    "title": "Keys & Colored Gates",
    "author": "Casual Maze Academy",
    "version": 1,
    "dimensions": {
      "width": 11,
      "height": 11
    },
    "config": {
      "fogOfWar": false,
      "mapRevealed": true,
      "viewRadius": 6,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "dungeon"
    },
    "help": {
      "title": "Color Keys & Gates",
      "message": "Gates block your path! Collect the Ruby Key in the side corridor to unlock the Red Gate, then find the Sapphire Key to open the Blue Gate to the exit."
    },
    "spawn": {
      "x": 1,
      "y": 1,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 9,
      "y": 9,
      "style": "portal"
    },
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          1,
          1
        ],
        [
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "key_red_t2",
        "type": "key",
        "x": 3,
        "y": 3,
        "color": "#f43f5e",
        "name": "Ruby Key",
        "style": "classic",
        "glowEffect": "vibrant"
      },
      {
        "id": "door_red_t2",
        "type": "door",
        "x": 1,
        "y": 5,
        "requiresKey": "key_red_t2",
        "color": "#f43f5e",
        "style": "classic",
        "orientation": "vertical"
      },
      {
        "id": "key_blue_t2",
        "type": "key",
        "x": 7,
        "y": 3,
        "color": "#38bdf8",
        "name": "Sapphire Crystal",
        "style": "crystal",
        "glowEffect": "pulse"
      },
      {
        "id": "door_blue_t2",
        "type": "door",
        "x": 7,
        "y": 7,
        "requiresKey": "key_blue_t2",
        "color": "#38bdf8",
        "style": "portcullis",
        "orientation": "horizontal"
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "tutorial_3",
    "title": "Mechanisms & Levers",
    "author": "Casual Maze Academy",
    "version": 1,
    "dimensions": {
      "width": 11,
      "height": 11
    },
    "config": {
      "fogOfWar": false,
      "mapRevealed": true,
      "viewRadius": 6,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "temple"
    },
    "help": {
      "title": "Interactive Switches",
      "message": "Floor levers dynamically mutate the labyrinth! Step onto or press E / Space near a switch to lower walls blocking your path."
    },
    "spawn": {
      "x": 1,
      "y": 1,
      "elevation": 0,
      "style": "archway"
    },
    "exit": {
      "x": 9,
      "y": 9,
      "style": "stairs_up"
    },
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          1,
          1,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "lever_t3_1",
        "type": "lever",
        "x": 3,
        "y": 7,
        "name": "Sanctuary Lever",
        "style": "switch_lever",
        "state": false,
        "targets": [
          {
            "action": "toggle_tile",
            "layer": "ground",
            "x": 5,
            "y": 5,
            "stateA": 0,
            "stateB": 1
          }
        ]
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "tutorial_4",
    "title": "Bridges & Elevation",
    "author": "Casual Maze Academy",
    "version": 1,
    "dimensions": {
      "width": 13,
      "height": 13
    },
    "config": {
      "fogOfWar": false,
      "mapRevealed": true,
      "viewRadius": 6,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "jungle"
    },
    "help": {
      "title": "3D Bridges & Underpasses",
      "message": "Bridges allow two paths to cross in 3D without intersecting! Walk East UNDER the bridge to reach the sun key in the upper canopy, then climb the ramp to cross OVER the bridge to reach the shrine."
    },
    "spawn": {
      "x": 1,
      "y": 1,
      "elevation": 0,
      "style": "camp"
    },
    "exit": {
      "x": 11,
      "y": 11,
      "style": "shrine"
    },
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          1,
          "R_S",
          1,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          "R_N",
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1
        ],
        [
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "key_gold_t4",
        "type": "key",
        "x": 11,
        "y": 1,
        "color": "#fbbf24",
        "name": "Sun Key",
        "style": "crystal",
        "glowEffect": "vibrant"
      },
      {
        "id": "door_gold_t4",
        "type": "door",
        "x": 10,
        "y": 11,
        "requiresKey": "key_gold_t4",
        "color": "#fbbf24",
        "style": "classic",
        "orientation": "vertical"
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "tutorial_5",
    "title": "The Shrouded Path",
    "author": "Casual Maze Academy",
    "version": 1,
    "dimensions": {
      "width": 13,
      "height": 13
    },
    "config": {
      "fogOfWar": true,
      "mapRevealed": true,
      "viewRadius": 4,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "dungeon"
    },
    "help": {
      "title": "Fog of War & Vision Radius",
      "message": "The maze layout is revealed in memory, but dynamic items (keys, doors, levers) stay hidden in the shadows until you are within 4 tiles of vision!"
    },
    "spawn": {
      "x": 1,
      "y": 1,
      "elevation": 0,
      "style": "stairs_down"
    },
    "exit": {
      "x": 11,
      "y": 11,
      "style": "portal"
    },
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "key_gold_t5",
        "type": "key",
        "x": 9,
        "y": 3,
        "color": "#fbbf24",
        "name": "Crypt Bone Token",
        "style": "skull",
        "glowEffect": "pulse"
      },
      {
        "id": "door_gold_t5",
        "type": "door",
        "x": 9,
        "y": 9,
        "requiresKey": "key_gold_t5",
        "color": "#fbbf24",
        "style": "magic_seal",
        "orientation": "auto"
      }
    ]
  },
  {
    "$schema": "https://casual-maze-game.inbarrose.com/schemas/maze-v1.json",
    "id": "tutorial_6",
    "title": "Master's Trial",
    "author": "Casual Maze Academy",
    "version": 1,
    "dimensions": {
      "width": 17,
      "height": 17
    },
    "config": {
      "fogOfWar": true,
      "mapRevealed": false,
      "viewRadius": 5,
      "allowFreePan": true,
      "tileSize": 32,
      "theme": "temple"
    },
    "help": {
      "title": "The Master's Trial",
      "message": "The final test! Navigate the shrouded darkness, pass under the central bridge to retrieve the sapphire orb, then cross over the bridge deck to trigger mechanisms and claim victory."
    },
    "spawn": {
      "x": 1,
      "y": 1,
      "elevation": 0,
      "style": "archway"
    },
    "exit": {
      "x": 15,
      "y": 15,
      "style": "chest"
    },
    "layers": {
      "ground": [
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          "R_S",
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          "R_N",
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1
        ],
        [
          1,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          0,
          1
        ],
        [
          1,
          0,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1
        ],
        [
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1
        ],
        [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      ],
      "overhead": [
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          "B_EW",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "entities": [
      {
        "id": "key_green_t6",
        "type": "key",
        "x": 3,
        "y": 3,
        "color": "#34d399",
        "name": "Emerald Scarab",
        "style": "relic",
        "glowEffect": "vibrant"
      },
      {
        "id": "door_green_t6",
        "type": "door",
        "x": 4,
        "y": 1,
        "requiresKey": "key_green_t6",
        "color": "#34d399",
        "style": "portcullis",
        "orientation": "vertical"
      },
      {
        "id": "key_blue_t6",
        "type": "key",
        "x": 15,
        "y": 1,
        "color": "#38bdf8",
        "name": "Sapphire Orb",
        "style": "orb",
        "glowEffect": "pulse"
      },
      {
        "id": "door_blue_t6",
        "type": "door",
        "x": 11,
        "y": 11,
        "requiresKey": "key_blue_t6",
        "color": "#38bdf8",
        "style": "magic_seal",
        "orientation": "vertical"
      },
      {
        "id": "lever_t6",
        "type": "lever",
        "x": 11,
        "y": 12,
        "name": "Sanctuary Switch",
        "style": "pressure_pedestal",
        "state": false,
        "targets": [
          {
            "action": "toggle_tile",
            "layer": "ground",
            "x": 2,
            "y": 14,
            "stateA": 0,
            "stateB": 1
          }
        ]
      },
      {
        "id": "key_red_t6",
        "type": "key",
        "x": 1,
        "y": 15,
        "color": "#f43f5e",
        "name": "Ruby Sun Shard",
        "style": "crystal",
        "glowEffect": "vibrant"
      },
      {
        "id": "door_red_t6",
        "type": "door",
        "x": 14,
        "y": 15,
        "requiresKey": "key_red_t6",
        "color": "#f43f5e",
        "style": "vault_hatch",
        "orientation": "vertical"
      }
    ]
  }
]);
